name: Change Request
description: Request a change to code, FDS models, or documentation
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to request changes. For questions or discussion, please use [GitHub Discussions](https://github.com/hklittlefinger/hongkong-taipo-fire-fds-sim/discussions).

  - type: dropdown
    id: type
    attributes:
      label: Change Type
      description: What type of change are you requesting?
      options:
        - Code (scripts, infrastructure)
        - Model (FDS simulation files)
        - Documentation
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the change you're requesting
      placeholder: What change would you like to see?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this change needed?
      placeholder: What problem does this solve or what improvement does it bring?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches you've considered
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, references, or screenshots
    validations:
      required: false
